import type { ParkingSpot } from "@/lib/types";

// This is now used only for the initial structure. The status is updated by the API.
export const initialParkingSpots: ParkingSpot[] = [
  { id: "A1", status: "available" },
  { id: "A2", status: "available" },
  { id: "A3", status: "available" },
  { id: "A4", status: "available" },
  { id: "A5", status: "available" },
  { id: "A6", status: "available" },
  { id: "A7", status: "available" },
  { id: "A8", status: "available" },
  { id: "B1", status: "available" },
  { id: "B2", status: "available" },
  { id: "B3", status: "available" },
  { id: "B4", status: "available" },
  { id: "B5", status: "available" },
  { id: "B6", status: "available" },
  { id: "B7", status: "available" },
  { id: "C1", status: "available" },
  { id: "C2", status: "available" },
  { id: "C3", status: "available" },
  { id: "C4", status: "available" },
  { id: "C5", status: "available" },
  { id: "C6", status: "available" },
  { id: "D1", status: "available" },
  { id: "D2", status: "available" },
  { id: "D3", status: "available" },
  { id: "D4", status: "available" },
  { id: "D5", status: "available" },
];
